#!/usr/bin/env bash
day="$1"
part="$2"

set -e

compare() {
    d="$1"
    p="$2"
    ./prepare "$1" "$2"
    echo "Testing day $1 part $2"
    diff -w <(./run "$d" "$p" "inputs/input$d.txt") "outputs/${d}_${p}.out"
}

./clean

if [ -n "$day" ]; then
    if [ -n "$part" ]; then
        compare "$day" "$part"
    else
        compare "$day" "1"
        compare "$day" "2"
    fi
else
    i=1
    while [ -f "outputs/$(printf '%02d' $i)_1.out" ]; do
        compare "$(printf '%02d' $i)" "1"
        if [ -f "outputs/$(printf '%02d' $i)_2.out" ]; then
            compare "$(printf '%02d' $i)" "2"
        fi
        i=$((i+1))
    done
fi
