name: Run CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install MUSL
        run: sudo apt-get install -y musl musl-dev musl-tools
      - name: Run tests
        run: ./test
